name: Auto

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test and Lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Check go.mod and go.sum are tidy
        run: go mod tidy -diff

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -race -coverprofile=coverage.out ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.14.0
